#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
    buffer_index_type = 4
    windows_index_type = 3
    filemanager = "nerdtree"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'core'
filetree_show_hidden = true

[[layers]]
name = "lang#swift"

[[layers]]
name = "lang#markdown"

[[custom_plugins]]
name = 'wakatime/vim-wakatime'
enable = true

[[layers]]
name = "fzf"

[[layers]]
name = "VersionControl"

[[layers]]
name = "default"

[[layers]]
name = "git"
git_plugin = 'fugitive'
